### ISSUE TITLE
Oplevering Iteratie 3

### ISSUE THREAD

**Issue by Videntory** [jewelsz/Tank-war-Proftaak#24]
- [x] Projectdossier met urenverantwoording etc
- [ ] Projectdocumentatie
    - [x] Projectplan, 
    - [x] Analyse Document, 
    - [ ] Software Architectuur Document, 
    - [x] Systeemtestplan, 
    - [x] Testrapport, etc.
- [x] Source code met unittests inclusief coverage
- [ ] SonarQube rapportage #22 
- [x] Onderzoeksrapportage
- [x] Peerreviewformulier

Upload alles naar:
[Week 15: Oplevering Iteratie 3 (eerste versie gedistribueerde applicatie)](https://fhict.instructure.com/courses/7781/assignments/114049)
