### ISSUE TITLE
[Server] Game logic

### ISSUE THREAD

**Issue by Videntory** [jewelsz/Tank-war-Proftaak#3]
- [x] Add broadcasting of start game #14 
    - [x] Add broadcasting of tank spawn
- [x] Add broadcasting of tank movement #15 
- [x] Add broadcasting of tank projectiles #16 
- [x] Add broadcasting of tank despawn #20
- [x] Add broadcasting of user game leave 
- [x] Add broadcasting of end game #21
